apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: database

type: Opaque # echo -n "Roboshop1" | base64
data:
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3A="
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjM="

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop

  # deployment labels
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
spec:
  replicas: 1
  # 2 replica set use to create pod
  selector:
    matchLabels:
      component: rabbitmq
      project: roboshop
      tier: database
  template:
    metadata:
      labels:
        component: rabbitmq
        project: roboshop
        tier: database
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3
          envFrom:
            - secretRef:
                name: rabbitmq

  #---------------- service
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
spec:
  selector:
    component: rabbitmq
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
