apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    tier: database

type: Opaque # echo -n "Roboshop1" | base64
data:
  MYSQL_ROOT_PASSWORD: "Um9ib3Nob3BAMQ=="

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop

  # deployment labels
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  replicas: 1
  # 2 replica set use to create pod
  selector:
    matchLabels:
      component: mysql
      project: roboshop
      tier: database
  template:
    metadata:
      labels:
        component: mysql
        project: roboshop
        tier: database
    spec:
      containers:
        - name: mysql
          image: joindevops/mysql:v1
          envFrom:
            - secretRef:
                name: mysql

  #---------------- service
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    component: mysql
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
